### ISSUE TITLE
Module does not build with rustc 1.49

### ISSUE THREAD

**Issue by doragasu** [TNkemdilim/wifi-rs#7]
When cargo tries to build `wifi-rs`, it fails with following error:
```
   Compiling wifi-rs v0.2.1
error[E0599]: no variant or associated item named `CreationFailed` found for enum `WifiHotspotError` in the current scope
  --> /home/jalon/.cargo/registry/src/github.com-1ecc6299db9ec823/wifi-rs-0.2.1/src/hotspot/providers/linux.rs:77:47
   |
77 |             .map_err(|_err| WifiHotspotError::CreationFailed)?;
   |                                               ^^^^^^^^^^^^^^ variant or associated item not found in `WifiHotspotError`
   | 
  ::: /home/jalon/.cargo/registry/src/github.com-1ecc6299db9ec823/wifi-rs-0.2.1/src/hotspot/mod.rs:9:1
   |
9  | pub enum WifiHotspotError {
   | ------------------------- variant or associated item `CreationFailed` not found here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `wifi-rs`

To learn more, run the command again with --verbose.
```

Host is Archlinux with up to date stable Rust compiler version 1.49 (instaled via rustc).

This error happens with versions `0.2.0` and `0.2.1`. Version `0.1.0` builds nicely (but unfortunately seems not to work, running the example program I get a "Invalid password" message even though SSID and password are correct).

**Comment by TNkemdilim** [comment]
Hello @doragasu,

Apologies for the inconvenience. 

I'll look into it later (either today/tomorrow) and come up a fix.

**Comment by TNkemdilim** [comment]
Sorry for the delay. I've published a new release `0.2.2`.

Thanks once again for raising the issue.

**Comment by doragasu** [comment]
Thanks!
